# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 601)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QListWidget, QListView, QTreeWidget, QTreeView,QFrame {\n"
"    outline: 0px;\n"
"}\n"
"/*设置左侧选项的最小最大宽度,文字颜色和背景颜色*/\n"
"QListWidget {\n"
"    min-width: 200px;\n"
"    max-width: 200px;\n"
"    color: white;\n"
"    background-color:#2f4050\n"
"}\n"
"#head\n"
"{\n"
"background:white;\n"
"border-radius:30px;\n"
"}\n"
"#head_2\n"
"{\n"
"background:#CCFFCC;\n"
"border:1px solid;\n"
"border-color:#CCFFCC;\n"
"border-radius:60px;\n"
"}\n"
"#Search\n"
"{\n"
"border-radius:5px;\n"
"background:#293846;\n"
"border:0.5px solid;\n"
"border-color:white;\n"
"\n"
"}\n"
"QListWidget::item\n"
"{\n"
"height:60;\n"
"background-color:#293846;\n"
"}\n"
"#frame\n"
"{\n"
"background-color:#2f4050\n"
"\n"
"}\n"
"/*被选中时的背景颜色和左边框颜色*/\n"
"QListWidget::item:selected {\n"
"    background: rgb(52, 52, 52);\n"
"    border-left: 2px solid rgb(9, 187, 7);\n"
"}\n"
"/*鼠标悬停颜色*/\n"
"HistoryPanel::item:hover {\n"
"    background: rgb(52, 52, 52);\n"
"}\n"
"/*右侧的层叠窗口的背景颜色*/\n"
"QStackedWidget {\n"
"    background: white;\n"
"}\n"
"/*模拟的页面*/\n"
"#frame > QLabel\n"
"{\n"
"color:white;\n"
"}\n"
"#frame_2\n"
"{\n"
"background-color:#CCFFCC;\n"
"}\n"
"#page_2 > QLineEdit,QDateEdit\n"
"{\n"
"border-radius:5px;\n"
"background:#FFFFFF;\n"
"border:1px solid;\n"
"border-color:#6699CC;\n"
"}\n"
"#page_4 > QLineEdit\n"
"{\n"
"border-radius:5px;\n"
"background:#FFFFFF;\n"
"border:1px solid;\n"
"border-color:#6699CC;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 211, 201))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.head = QtWidgets.QToolButton(self.frame)
        self.head.setGeometry(QtCore.QRect(60, 20, 61, 61))
        self.head.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../pictures/staff3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.head.setIcon(icon)
        self.head.setIconSize(QtCore.QSize(60, 60))
        self.head.setObjectName("head")
        self.welcome = QtWidgets.QLabel(self.frame)
        self.welcome.setGeometry(QtCore.QRect(30, 90, 110, 20))
        self.welcome.setText("")
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(6)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Search = QtWidgets.QLineEdit(self.frame)
        self.Search.setGeometry(QtCore.QRect(20, 170, 145, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 227, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 227, 226, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 227, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 227, 226, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 56, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Search.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        font.setStrikeOut(False)
        self.Search.setFont(font)
        self.Search.setAutoFillBackground(False)
        self.Search.setStyleSheet("")
        self.Search.setObjectName("Search")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(170, 170, 21, 20))
        self.toolButton.setStyleSheet("background-color:#2f4050;\n"
"border:0px;\n"
"\n"
"border-radius:5px")
        self.toolButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../pictures/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setIconSize(QtCore.QSize(15, 15))
        self.toolButton.setObjectName("toolButton")
        self.role = QtWidgets.QLabel(self.frame)
        self.role.setGeometry(QtCore.QRect(30, 120, 110, 15))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.role.setFont(font)
        self.role.setText("")
        self.role.setAlignment(QtCore.Qt.AlignCenter)
        self.role.setObjectName("role")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(200, 0, 611, 601))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tableClient = QtWidgets.QTableWidget(self.page_3)
        self.tableClient.setGeometry(QtCore.QRect(0, 260, 611, 341))
        self.tableClient.setStyleSheet("background-color: rgba(255, 255, 255, 222)")
        self.tableClient.setObjectName("tableClient")
        self.tableClient.setColumnCount(7)
        self.tableClient.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableClient.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableClient.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableClient.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableClient.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableClient.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableClient.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableClient.setHorizontalHeaderItem(6, item)
        self.frame_2 = QtWidgets.QFrame(self.page_3)
        self.frame_2.setGeometry(QtCore.QRect(0, 30, 611, 231))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("background-color: rgba(255, 255, 255, 222)\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.searchName = QtWidgets.QLineEdit(self.frame_2)
        self.searchName.setGeometry(QtCore.QRect(230, 80, 211, 31))
        self.searchName.setStyleSheet("border-radius:10px;\n"
"background:#FFFFFF;\n"
"border:1px solid;\n"
"border-color:#CCCCFF;\n"
"")
        self.searchName.setObjectName("searchName")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(160, 70, 61, 41))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setGeometry(QtCore.QRect(130, 110, 121, 51))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_24.setObjectName("label_24")
        self.searchTimes = QtWidgets.QLineEdit(self.frame_2)
        self.searchTimes.setGeometry(QtCore.QRect(230, 120, 211, 31))
        self.searchTimes.setStyleSheet("border-radius:10px;\n"
"background:#FFFFFF;\n"
"border:1px solid;\n"
"border-color:#CCCCFF;\n"
"")
        self.searchTimes.setObjectName("searchTimes")
        self.typeC = QtWidgets.QRadioButton(self.frame_2)
        self.typeC.setGeometry(QtCore.QRect(240, 30, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.typeC.setFont(font)
        self.typeC.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.typeC.setObjectName("typeC")
        self.typeT = QtWidgets.QRadioButton(self.frame_2)
        self.typeT.setGeometry(QtCore.QRect(350, 30, 115, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.typeT.setFont(font)
        self.typeT.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.typeT.setObjectName("typeT")
        self.label_78 = QtWidgets.QLabel(self.frame_2)
        self.label_78.setGeometry(QtCore.QRect(130, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_78.setObjectName("label_78")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(20, 10, 571, 201))
        self.frame_3.setStyleSheet("background-color: rgba(194, 197, 196, 102);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.searchNB = QtWidgets.QToolButton(self.frame_3)
        self.searchNB.setGeometry(QtCore.QRect(210, 150, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searchNB.setFont(font)
        self.searchNB.setStyleSheet("background-color: rgb(76, 100, 186);\n"
"color: rgb(255, 255, 255);\n"
"border:0px;\n"
"\n"
"border-radius:5px")
        self.searchNB.setIcon(icon1)
        self.searchNB.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.searchNB.setObjectName("searchNB")
        self.tableDelB = QtWidgets.QToolButton(self.frame_3)
        self.tableDelB.setGeometry(QtCore.QRect(320, 150, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableDelB.setFont(font)
        self.tableDelB.setStyleSheet("background-color: rgb(76, 100, 186);\n"
"border:0px;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px")
        self.tableDelB.setIcon(icon1)
        self.tableDelB.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tableDelB.setObjectName("tableDelB")
        self.frame_3.raise_()
        self.searchName.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.searchTimes.raise_()
        self.typeC.raise_()
        self.typeT.raise_()
        self.label_78.raise_()
        self.toolButton_2 = QtWidgets.QToolButton(self.page_3)
        self.toolButton_2.setGeometry(QtCore.QRect(0, 0, 611, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setStyleSheet("background-color: rgb(76, 100, 186);\n"
"color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../pictures/search1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.split_2 = QtWidgets.QFrame(self.page_2)
        self.split_2.setGeometry(QtCore.QRect(0, 30, 600, 2))
        self.split_2.setStyleSheet("color:#CCFFCC;\n"
"border-color:#CCFFCC;\n"
"background-color:#CCFFCC")
        self.split_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.split_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.split_2.setObjectName("split_2")
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setGeometry(QtCore.QRect(100, 280, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(100, 370, 101, 41))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_13.setObjectName("label_13")
        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setGeometry(QtCore.QRect(100, 420, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_2)
        self.label_17.setGeometry(QtCore.QRect(100, 470, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.cname = QtWidgets.QLineEdit(self.page_2)
        self.cname.setGeometry(QtCore.QRect(220, 280, 221, 31))
        self.cname.setObjectName("cname")
        self.cid = QtWidgets.QLineEdit(self.page_2)
        self.cid.setGeometry(QtCore.QRect(220, 430, 221, 21))
        self.cid.setObjectName("cid")
        self.cphone = QtWidgets.QLineEdit(self.page_2)
        self.cphone.setGeometry(QtCore.QRect(220, 480, 221, 21))
        self.cphone.setObjectName("cphone")
        self.toolButton_3 = QtWidgets.QToolButton(self.page_2)
        self.toolButton_3.setGeometry(QtCore.QRect(0, 0, 621, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setStyleSheet("background-color: rgb(76, 100, 186);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../pictures/insert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon3)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.commitAdd = QtWidgets.QPushButton(self.page_2)
        self.commitAdd.setGeometry(QtCore.QRect(240, 530, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.commitAdd.setFont(font)
        self.commitAdd.setStyleSheet("background-color: rgb(76, 100, 186);\n"
"color: rgb(255, 255, 255);")
        self.commitAdd.setObjectName("commitAdd")
        self.cfemale = QtWidgets.QRadioButton(self.page_2)
        self.cfemale.setGeometry(QtCore.QRect(320, 380, 115, 19))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cfemale.setFont(font)
        self.cfemale.setObjectName("cfemale")
        self.cmale = QtWidgets.QRadioButton(self.page_2)
        self.cmale.setGeometry(QtCore.QRect(220, 380, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cmale.setFont(font)
        self.cmale.setObjectName("cmale")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(100, 320, 101, 41))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.cage = QtWidgets.QLineEdit(self.page_2)
        self.cage.setGeometry(QtCore.QRect(220, 330, 221, 21))
        self.cage.setObjectName("cage")
        self.line_2 = QtWidgets.QFrame(self.page_2)
        self.line_2.setGeometry(QtCore.QRect(0, 240, 611, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tid = QtWidgets.QLineEdit(self.page_2)
        self.tid.setGeometry(QtCore.QRect(230, 110, 221, 21))
        self.tid.setObjectName("tid")
        self.tphone = QtWidgets.QLineEdit(self.page_2)
        self.tphone.setGeometry(QtCore.QRect(230, 160, 221, 21))
        self.tphone.setObjectName("tphone")
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setGeometry(QtCore.QRect(110, 50, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(110, 150, 101, 41))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.tname = QtWidgets.QLineEdit(self.page_2)
        self.tname.setGeometry(QtCore.QRect(230, 60, 221, 21))
        self.tname.setObjectName("tname")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(110, 100, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_15.setObjectName("label_15")
        self.commitAddT = QtWidgets.QPushButton(self.page_2)
        self.commitAddT.setGeometry(QtCore.QRect(250, 190, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.commitAddT.setFont(font)
        self.commitAddT.setStyleSheet("background-color: rgb(76, 100, 186);\n"
"color: rgb(255, 255, 255);")
        self.commitAddT.setObjectName("commitAddT")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(30, 260, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.label_10.setObjectName("label_10")
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 40, 581, 201))
        self.frame_4.setStyleSheet("background-color: rgba(194, 197, 196, 102);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.page_2)
        self.frame_5.setGeometry(QtCore.QRect(10, 260, 581, 321))
        self.frame_5.setStyleSheet("background-color: rgba(194, 197, 196, 102);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_5.raise_()
        self.frame_4.raise_()
        self.split_2.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.cname.raise_()
        self.cid.raise_()
        self.cphone.raise_()
        self.toolButton_3.raise_()
        self.commitAdd.raise_()
        self.cfemale.raise_()
        self.cmale.raise_()
        self.label_12.raise_()
        self.cage.raise_()
        self.line_2.raise_()
        self.tid.raise_()
        self.tphone.raise_()
        self.label_14.raise_()
        self.label_18.raise_()
        self.tname.raise_()
        self.label_15.raise_()
        self.commitAddT.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(-4, 200, 204, 401))
        self.listWidget.setStyleSheet("")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../pictures/customer2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../pictures/customer1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.listWidget.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "*表示需要最高权限"))
        self.Search.setText(_translate("MainWindow", "搜索"))
        self.Search.setPlaceholderText(_translate("MainWindow", "搜索"))
        item = self.tableClient.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.tableClient.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "性别"))
        item = self.tableClient.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "注册时间"))
        item = self.tableClient.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "年龄"))
        item = self.tableClient.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "身份证号"))
        item = self.tableClient.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "手机号"))
        item = self.tableClient.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "入住次数"))
        self.searchName.setPlaceholderText(_translate("MainWindow", "搜索员工姓名"))
        self.label_23.setText(_translate("MainWindow", "姓名："))
        self.label_24.setText(_translate("MainWindow", "入住次数："))
        self.searchTimes.setPlaceholderText(_translate("MainWindow", "入住次数"))
        self.typeC.setText(_translate("MainWindow", "散客"))
        self.typeT.setText(_translate("MainWindow", "团队"))
        self.label_78.setText(_translate("MainWindow", "客人类型"))
        self.searchNB.setText(_translate("MainWindow", "立即检索"))
        self.tableDelB.setText(_translate("MainWindow", "删除"))
        self.toolButton_2.setText(_translate("MainWindow", "查询客户"))
        self.label_11.setText(_translate("MainWindow", "客户姓名"))
        self.label_13.setText(_translate("MainWindow", "客户性别"))
        self.label_16.setText(_translate("MainWindow", "身份证"))
        self.label_17.setText(_translate("MainWindow", "手机号"))
        self.cname.setPlaceholderText(_translate("MainWindow", "姓名"))
        self.cid.setPlaceholderText(_translate("MainWindow", "身份证"))
        self.cphone.setPlaceholderText(_translate("MainWindow", "手机号"))
        self.toolButton_3.setText(_translate("MainWindow", "增添客户"))
        self.commitAdd.setText(_translate("MainWindow", "确认录入"))
        self.cfemale.setText(_translate("MainWindow", "女"))
        self.cmale.setText(_translate("MainWindow", "男"))
        self.label_12.setText(_translate("MainWindow", "客户年龄"))
        self.cage.setPlaceholderText(_translate("MainWindow", "年龄"))
        self.tid.setPlaceholderText(_translate("MainWindow", "标识"))
        self.tphone.setPlaceholderText(_translate("MainWindow", "手机号"))
        self.label_14.setText(_translate("MainWindow", "团队名称"))
        self.label_18.setText(_translate("MainWindow", "预留手机号"))
        self.tname.setPlaceholderText(_translate("MainWindow", "名称"))
        self.label_15.setText(_translate("MainWindow", "团队标识"))
        self.commitAddT.setText(_translate("MainWindow", "确认录入"))
        self.label_9.setText(_translate("MainWindow", "团队客人"))
        self.label_10.setText(_translate("MainWindow", "散客"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "  增加客户"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "  查询和删除客户"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
